DROP TABLE IF EXISTS audit;

CREATE TABLE audit (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(100) NOT NULL,
  request_date TIMESTAMP DEFAULT CURRENT_DATE,
  method_executed VARCHAR(250) DEFAULT NULL
);


